import type { Course } from '~/types/feature-card';

export const coursesData: Course[] = [
    {
        id: 1,
        title: 'Data Competitive Strategy Law & Organization',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c1.png',
        level: 'Advance',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 2,
        title: 'Transform Your Company : Strategic Guidance',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c2.png',
        level: 'Beginner',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 3,
        title: 'Graphic Design Basics : learn the Foundations of Visual',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c3.png',
        level: 'Intermediate',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 4,
        title: "A Beginner's Guide to Building Your Online Presence",
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c4.png',
        level: 'Advance',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 5,
        title: 'Data Competitive Strategy Law & Organization',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c5.png',
        level: 'Advance',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 6,
        title: 'Transform Your Company : Strategic Guidance',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c6.png',
        level: 'Beginner',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 7,
        title: 'Graphic Design Basics : learn the Foundations of Visual',
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c7.png',
        level: 'Intermediate',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
    {
        id: 8,
        title: "A Beginner's Guide to Building Your Online Presence",
        price: 'GHC 240.00',
        rating: 4.5,
        reviewCount: 125,
        image: '/courses/c8.png',
        level: 'Advance',
        lessonCount: 120,
        duration: '12h, 55mins',
    },
];
